FROM ubuntu:latest as work_market_image
RUN apt update
RUN apt upgrade -y
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y make
RUN apt-get install -y cmake
RUN mkdir /devel/
RUN mkdir /devel/work_market/
RUN apt-get install -y libcurl4-openssl-dev

#adding spdlog
#RUN mkdir -p /home/libs/spdlog/build 
RUN apt-get install git -y 
RUN git clone https://github.com/gabime/spdlog.git /home/libs/spdlog/
RUN cmake -S /home/libs/spdlog/ -B /home/libs/spdlog/build/ 
RUN make /home/libs/spdlog/build/  
RUN mkdir /home/logs/

###sql
RUN apt-get install mysql-server
RUN apt-get install libmysqlclient-dev
RUN service mysql start
RUN mysql
RUN ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
RUN exit

#getting wget
RUN apt-get install -y wget

#getting bzip
RUN apt-get install -y bzip2

#boost
RUN mkdir /home/libs/boost
RUN wget --continue --directory-prefix=/home/libs/boost/ https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.bz2
RUN tar --directory=/home/libs/boost/ --checkpoint=1000 --bzip2 -xf /home/libs/boost/boost_1_82_0.tar.bz2
RUN cd /home/libs/boost/boost_1_82_0/
RUN ./bootstrap.sh
RUN ./b2 install

RUN apt-get install -y pkg-config
RUN apt-get install dpkg-dev

RUN apt-get install libmysqlcppconn-dev

#if not enoght cloning from git-hub

#for compilation image:  docker build . -f dockerfile.txt -t work_market_image

#docker run --name work_market -v "$(pwd)":/devel/work_market -it ubuntu:latest /bin/bash

#docker exec -it work_market bash

#pass root

RUN mysql -u root -p
